#!/usr/bin/env python3
"""Validate SOL-Lite source-pack invariants without third-party dependencies."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

VERSION_RE = re.compile(r"^version = \"([^\"]+)\"$", re.MULTILINE)
REQUIRED = (
    "pyproject.toml",
    "README.md",
    "config/sol-lite.yaml",
    "src/sol_lite/app.py",
    "src/sol_lite/agents/runtime.py",
    "src/sol_lite/agents/shell.py",
    "src/sol_lite/core/tasks.py",
    "src/sol_lite/security/command_guard.py",
    "src/sol_lite/tools/context.py",
    "src/sol_lite/tools/skills.py",
    "install/common/install.py",
    "launcher/windows/SOL-Lite.cmd",
    "launcher/macos/SOL-Lite.app/Contents/MacOS/SOL-Lite",
    "references/colour-wheel.md",
)
FORBIDDEN_PARTS = {".pytest_cache", "__pycache__", ".ruff_cache", ".mypy_cache", ".venv"}
FORBIDDEN_FILES = {"faults.json"}


def payload_files(root: Path) -> list[Path]:
    return sorted(
        path.relative_to(root)
        for path in root.rglob("*")
        if path.is_file() and not (set(path.parts) & FORBIDDEN_PARTS) and path.name not in FORBIDDEN_FILES and path.name not in {"*.pyc"}
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    root = args.root.resolve()
    errors: list[str] = []

    for relative in REQUIRED:
        if not (root / relative).is_file():
            errors.append(f"Missing required file: {relative}")

    pyproject = (root / "pyproject.toml").read_text(encoding="utf-8")
    match = VERSION_RE.search(pyproject)
    if not match:
        errors.append("Unable to determine project version from pyproject.toml")
    else:
        version = match.group(1)
        version_file = (root / "src/sol_lite/version.py").read_text(encoding="utf-8")
        config = (root / "config/sol-lite.yaml").read_text(encoding="utf-8")
        readme = (root / "README.md").read_text(encoding="utf-8")
        if f'__version__ = "{version}"' not in version_file:
            errors.append("src/sol_lite/version.py does not match pyproject.toml")
        if f'version: "{version}"' not in config:
            errors.append("config/sol-lite.yaml does not match pyproject.toml")
        if not readme.startswith(f"# SOL-Lite v{version}"):
            errors.append("README.md version heading does not match pyproject.toml")

    for path in payload_files(root):
        if path.suffix == ".pyc" or path.name.endswith(".pyc"):
            errors.append(f"Generated bytecode is present in pack: {path.as_posix()}")

    manifest_path = root / "BUILD_MANIFEST.json"
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            listed = {entry["path"] for entry in manifest.get("files", [])}
            actual = {p.as_posix() for p in payload_files(root) if p.as_posix() != "BUILD_MANIFEST.json"}
            if listed != actual:
                missing = sorted(actual - listed)
                extra = sorted(listed - actual)
                if missing:
                    errors.append(f"Manifest missing files: {', '.join(missing)}")
                if extra:
                    errors.append(f"Manifest contains absent files: {', '.join(extra)}")
            for entry in manifest.get("files", []):
                path = root / entry["path"]
                if path.is_file() and sha256(path) != entry["sha256"]:
                    errors.append(f"Manifest hash mismatch: {entry['path']}")
        except (OSError, json.JSONDecodeError, KeyError, TypeError):
            errors.append("BUILD_MANIFEST.json is invalid")

    if errors:
        for error in errors:
            print(f"AUDIT ERROR: {error}")
        return 1
    print("SOL-Lite pack audit: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
